import Auth0
import Foundation
import Combine

/// Request model for confirming TOTP enrollment.
///
/// Contains all the necessary information to verify the TOTP enrollment
/// by providing the one-time password generated by the user's authenticator app.
struct ConfirmTOTPEnrollmentRequest {
    /// Access token for authenticating with Auth0's My Account API
    let token: String
    /// Auth0 tenant domain (e.g., "example.auth0.com")
    let domain: String
    /// The enrollment ID from the initial challenge
    let id: String
    /// The authentication session identifier from the challenge
    let authSession: String
    /// The 6-digit OTP code from the user's authenticator app
    let otpCode: String
}

/// Protocol for the TOTP enrollment confirmation use case.
protocol ConfirmTOTPEnrollmentUseCaseable {
    /// The URLSession used for network requests
    var session: URLSession { get }
    /// Confirms TOTP enrollment with the OTP code.
    ///
    /// - Parameter request: The request containing enrollment details and OTP code
    /// - Returns: The created authentication method
    /// - Throws: Auth0 or network errors if the operation fails
    func execute(request: ConfirmTOTPEnrollmentRequest) async throws -> AuthenticationMethod
}

/// Use case for confirming TOTP (Time-based One-Time Password) enrollment.
///
/// Verifies the TOTP enrollment by validating the one-time password generated
/// by the user's authenticator app. Upon successful verification, the TOTP
/// authentication method is enrolled for the user's account.
struct ConfirmTOTPEnrollmentUseCase: ConfirmTOTPEnrollmentUseCaseable {
    /// The URLSession used for network requests
    var session: URLSession

    /// Initializes the use case with an optional URLSession.
    ///
    /// - Parameter session: The URLSession to use for requests (defaults to .shared)
    init(session: URLSession = .shared) {
        self.session = session
    }

    /// Confirms TOTP enrollment with the provided OTP code.
    ///
    /// - Parameter request: Request containing enrollment details and OTP code
    /// - Returns: The newly created TOTP authentication method
    /// - Throws: Auth0APIError if the OTP is invalid or the request fails
    func execute(request: ConfirmTOTPEnrollmentRequest) async throws -> AuthenticationMethod {
        try await Auth0.myAccount(token: request.token, domain: request.domain, session: session)
            .authenticationMethods
            .confirmTOTPEnrollment(id: request.id, authSession: request.authSession, otpCode: request.otpCode)
            .start()
    }
}
